production:
  adapter: postgresql
  host: localhost
  database: band-aider
  username: <%= ENV['BAND_AIDER_POSTGRES_USERNAME'] %>
  password: <%= ENV['BAND_AIDER_POSTGRES_PASSWORD'] %>

development:
  adapter:  postgresql
  host:     localhost
  database: band-aider_development
  username: band-aider
  password:

test:
  adapter:  postgresql
  host:     localhost
  database: band-aider_test
  username: band-aider
  password:
